// Automatically generated by cn.argento.askia.compiler.annotation.DynamicCompilerTaskToStringAnnotationProcessor
// Thanks for core java 11, it is a excellent book to read!!!

package cn.argento.askia.compiler.annotation;
public class ToStrings {
    public static String toString(cn.argento.askia.compiler.annotation.User obj) {
        StringBuilder result = new StringBuilder();
        result.append("[");
        result.append("Name=");
        result.append(toString(obj.getName()));
        result.append("Address=");
        result.append(toString(obj.getAddress()));
        result.append("Id=");
        result.append(toString(obj.getId()));
        result.append("]");
        return result.toString();
    }
    public static String toString(Object obj) {
        return java.util.Objects.toString(obj);
    }
}
