package cn.argentoaskia.awt.widgets.apis.component;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;

public class ButtonAttributes {
    private JPanel main;
    private JSplitPane content;
    private JPanel buttons;
    private JButton b6;
    private JButton b5;
    private JButton b1;
    private JButton b0;
    private JButton b2;
    private JButton b3;
    private JButton b7;
    private JButton b8;
    private JButton b4;
    private JButton b10;
    private JButton b11;
    private JButton b12;
    private JButton b13;
    private JButton b9;
    private JButton b14;
    private JButton b15;
    private JButton b20;
    private JButton b16;
    private JButton b21;
    private JButton b17;
    private JButton b22;
    private JButton b18;
    private JButton b23;
    private JButton b19;
    private JButton b24;
    private JPanel control;
    private JPanel update;
    private JButton updateButton;
    private JButton resetButton;
    private JTextField actionCommandTextField;
    private JComboBox<String> buttonSelectComboBox;
    private JButton backgroundColorChooserButton;
    private JComboBox<String> cursorComboBox;
    private JCheckBox enabledCheckBox;
    private JButton fontSelectButton;
    private JButton foregroundColorChooserButton;
    private JCheckBox visibleCheckBox;
    private JTextField textTextField;
    private JTextField nameTextField;
    private JTextField preferredWidth;
    private JTextField preferredHeight;
    private JButton iconButton;
    private JTextField toolTipsTextField;

    private HashMap<String, JButton> buttonHashMap;

    private void createUIComponents() {
        // TODO: place custom component creation code here

    }

    private void initButtonMap() {
        buttonHashMap = new HashMap<>();
        buttonHashMap.put("Button0", b0);
        buttonHashMap.put("Button1", b1);
        buttonHashMap.put("Button2", b2);
        buttonHashMap.put("Button3", b3);
        buttonHashMap.put("Button4", b4);
        buttonHashMap.put("Button5", b5);
        buttonHashMap.put("Button6", b6);
        buttonHashMap.put("Button7", b7);
        buttonHashMap.put("Button8", b8);
        buttonHashMap.put("Button9", b9);
        buttonHashMap.put("Button10", b10);
        buttonHashMap.put("Button11", b11);
        buttonHashMap.put("Button12", b12);
        buttonHashMap.put("Button13", b13);
        buttonHashMap.put("Button14", b14);
        buttonHashMap.put("Button15", b15);
        buttonHashMap.put("Button16", b16);
        buttonHashMap.put("Button17", b17);
        buttonHashMap.put("Button18", b18);
        buttonHashMap.put("Button19", b19);
        buttonHashMap.put("Button20", b20);
        buttonHashMap.put("Button21", b21);
        buttonHashMap.put("Button22", b22);
        buttonHashMap.put("Button23", b23);
        buttonHashMap.put("Button24", b24);
    }

    private void bindButtonAttributesToControl(JButton button) {
        String actionCommand = button.getActionCommand();
        Color background = button.getBackground();
        Cursor cursor = button.getCursor();
        boolean enabled = button.isEnabled();
        Font font = button.getFont();
        Color foreground = button.getForeground();
        String text = button.getText();
        String name = button.getName();
        Dimension preferredSize = button.getPreferredSize();
        boolean visible = button.isVisible();
        Icon icon = button.getIcon();
        String toolTipText = button.getToolTipText();
        actionCommandTextField.setText(actionCommand);
        backgroundColorChooserButton.setBackground(background);
        backgroundColorChooserButton.setText("RGB(" + background.getRed() + "," + background.getGreen() + "," + background.getBlue() + ")");
        cursorComboBox.setSelectedIndex(cursor.getType());
        if (enabled) {
            enabledCheckBox.setSelected(true);
        } else {
            enabledCheckBox.setSelected(false);
        }
        foregroundColorChooserButton.setBackground(foreground);
        foregroundColorChooserButton.setText("RGB(" + foreground.getRed() + "," + foreground.getGreen() + "," + foreground.getBlue() + ")");
        textTextField.setText(text);
        nameTextField.setText(name);
        preferredWidth.setText(String.valueOf(preferredSize.width));
        preferredHeight.setText(String.valueOf(preferredSize.height));
        if (visible) {
            visibleCheckBox.setSelected(true);
        } else {
            visibleCheckBox.setSelected(false);
        }
        toolTipsTextField.setToolTipText(toolTipText);
    }

    private JButton getSelectedButton() {
        Object selectedItem = buttonSelectComboBox.getSelectedItem();
        JButton jButton = buttonHashMap.get(selectedItem);
        return jButton;
    }

    public ButtonAttributes() {
        initButtonMap();
        buttonSelectComboBox.addActionListener(e -> {
            JButton selectedButton = getSelectedButton();
            bindButtonAttributesToControl(selectedButton);
        });
        updateButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String text = actionCommandTextField.getText();
                JButton selectedButton = getSelectedButton();
                selectedButton.setText(text);
                selectedButton.repaint();
            }
        });
    }


    public static void main(String[] args) {
        JFrame windows = new JFrame("Button属性演示窗口");
        windows.setContentPane(new ButtonAttributes().main);
        windows.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        windows.pack();
        windows.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new BorderLayout(0, 0));
        update = new JPanel();
        update.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        main.add(update, BorderLayout.SOUTH);
        updateButton = new JButton();
        updateButton.setText("update");
        update.add(updateButton);
        resetButton = new JButton();
        resetButton.setText("reset");
        update.add(resetButton);
        content = new JSplitPane();
        main.add(content, BorderLayout.CENTER);
        buttons = new JPanel();
        buttons.setLayout(new GridBagLayout());
        buttons.putClientProperty("html.disable", Boolean.TRUE);
        content.setRightComponent(buttons);
        b6 = new JButton();
        b6.setText("Button6");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b6, gbc);
        b5 = new JButton();
        b5.setText("Button5");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b5, gbc);
        b1 = new JButton();
        b1.setText("Button1");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b1, gbc);
        b2 = new JButton();
        b2.setText("Button2");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b2, gbc);
        b3 = new JButton();
        b3.setText("Button3");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b3, gbc);
        b7 = new JButton();
        b7.setText("Button7");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b7, gbc);
        b8 = new JButton();
        b8.setText("Button8");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 2;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b8, gbc);
        b4 = new JButton();
        b4.setText("Button4");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 0;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b4, gbc);
        b10 = new JButton();
        b10.setText("Button10");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b10, gbc);
        b11 = new JButton();
        b11.setText("Button11");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b11, gbc);
        b12 = new JButton();
        b12.setText("Button12");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b12, gbc);
        b13 = new JButton();
        b13.setText("Button13");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 4;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b13, gbc);
        b9 = new JButton();
        b9.setText("Button9");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 2;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b9, gbc);
        b14 = new JButton();
        b14.setText("Button14");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 4;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b14, gbc);
        b15 = new JButton();
        b15.setText("Button15");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b15, gbc);
        b20 = new JButton();
        b20.setText("Button20");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b20, gbc);
        b16 = new JButton();
        b16.setText("Button16");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b16, gbc);
        b21 = new JButton();
        b21.setText("Button21");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b21, gbc);
        b17 = new JButton();
        b17.setText("Button17");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 6;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b17, gbc);
        b22 = new JButton();
        b22.setText("Button22");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 8;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b22, gbc);
        b18 = new JButton();
        b18.setText("Button18");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 6;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b18, gbc);
        b23 = new JButton();
        b23.setText("Button23");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 8;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b23, gbc);
        b19 = new JButton();
        b19.setText("Button19");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 6;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b19, gbc);
        b24 = new JButton();
        b24.setText("Button24");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 8;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b24, gbc);
        b0 = new JButton();
        b0.setText("Button0");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        buttons.add(b0, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttons.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttons.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttons.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttons.add(spacer4, gbc);
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setText("Button0");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        buttons.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setHorizontalAlignment(0);
        label2.setHorizontalTextPosition(0);
        label2.setText("Button1");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        buttons.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Button2");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        buttons.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Button3");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 1;
        buttons.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Button4");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 1;
        buttons.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Button5");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        buttons.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Button6");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        buttons.add(label7, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Button7");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        buttons.add(label8, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Button8");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 3;
        buttons.add(label9, gbc);
        final JLabel label10 = new JLabel();
        label10.setText("Button9");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 3;
        buttons.add(label10, gbc);
        final JLabel label11 = new JLabel();
        label11.setText("Button10");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        buttons.add(label11, gbc);
        final JLabel label12 = new JLabel();
        label12.setText("Button11");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        buttons.add(label12, gbc);
        final JLabel label13 = new JLabel();
        label13.setText("Button12");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        buttons.add(label13, gbc);
        final JLabel label14 = new JLabel();
        label14.setText("Button13");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 5;
        buttons.add(label14, gbc);
        final JLabel label15 = new JLabel();
        label15.setText("Button14");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 5;
        buttons.add(label15, gbc);
        final JLabel label16 = new JLabel();
        label16.setText("Button15");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        buttons.add(label16, gbc);
        final JLabel label17 = new JLabel();
        label17.setText("Button16");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        buttons.add(label17, gbc);
        final JLabel label18 = new JLabel();
        label18.setText("Button17");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 7;
        buttons.add(label18, gbc);
        final JLabel label19 = new JLabel();
        label19.setText("Button18");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 7;
        buttons.add(label19, gbc);
        final JLabel label20 = new JLabel();
        label20.setText("Button19");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 7;
        buttons.add(label20, gbc);
        final JLabel label21 = new JLabel();
        label21.setText("Button20");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        buttons.add(label21, gbc);
        final JLabel label22 = new JLabel();
        label22.setText("Button21");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        buttons.add(label22, gbc);
        final JLabel label23 = new JLabel();
        label23.setText("Button22");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 9;
        buttons.add(label23, gbc);
        final JLabel label24 = new JLabel();
        label24.setText("Button23");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 9;
        buttons.add(label24, gbc);
        final JLabel label25 = new JLabel();
        label25.setText("Button24");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 9;
        buttons.add(label25, gbc);
        control = new JPanel();
        control.setLayout(new GridBagLayout());
        content.setLeftComponent(control);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.gridheight = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        control.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridheight = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        control.add(spacer6, gbc);
        actionCommandTextField = new JTextField();
        actionCommandTextField.setMinimumSize(new Dimension(61, 20));
        actionCommandTextField.setOpaque(false);
        actionCommandTextField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 100.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        control.add(actionCommandTextField, gbc);
        final JLabel label26 = new JLabel();
        label26.setText("ActionCommand：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        control.add(label26, gbc);
        final JLabel label27 = new JLabel();
        label27.setText("Target：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(label27, gbc);
        buttonSelectComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Button0");
        defaultComboBoxModel1.addElement("Button1");
        defaultComboBoxModel1.addElement("Button2");
        defaultComboBoxModel1.addElement("Button3");
        defaultComboBoxModel1.addElement("Button4");
        defaultComboBoxModel1.addElement("Button5");
        defaultComboBoxModel1.addElement("Button6");
        defaultComboBoxModel1.addElement("Button7");
        defaultComboBoxModel1.addElement("Button8");
        defaultComboBoxModel1.addElement("Button9");
        defaultComboBoxModel1.addElement("Button10");
        defaultComboBoxModel1.addElement("Button11");
        defaultComboBoxModel1.addElement("Button12");
        defaultComboBoxModel1.addElement("Button13");
        defaultComboBoxModel1.addElement("Button14");
        defaultComboBoxModel1.addElement("Button15");
        defaultComboBoxModel1.addElement("Button16");
        defaultComboBoxModel1.addElement("Button17");
        defaultComboBoxModel1.addElement("Button18");
        defaultComboBoxModel1.addElement("Button19");
        defaultComboBoxModel1.addElement("Button20");
        defaultComboBoxModel1.addElement("Button21");
        defaultComboBoxModel1.addElement("Button22");
        defaultComboBoxModel1.addElement("Button23");
        defaultComboBoxModel1.addElement("Button24");
        buttonSelectComboBox.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 100.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        control.add(buttonSelectComboBox, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer8, gbc);
        final JLabel label28 = new JLabel();
        label28.setText("BackGround：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.EAST;
        control.add(label28, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer9, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer10, gbc);
        backgroundColorChooserButton = new JButton();
        backgroundColorChooserButton.setText("Button");
        backgroundColorChooserButton.setVisible(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        control.add(backgroundColorChooserButton, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer11, gbc);
        final JPanel spacer12 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer12, gbc);
        final JLabel label29 = new JLabel();
        label29.setText("Cursor：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.EAST;
        control.add(label29, gbc);
        final JPanel spacer13 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer13, gbc);
        final JPanel spacer14 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer14, gbc);
        final JLabel label30 = new JLabel();
        label30.setText("Enabled：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.EAST;
        control.add(label30, gbc);
        final JPanel spacer15 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer15, gbc);
        final JPanel spacer16 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer16, gbc);
        final JLabel label31 = new JLabel();
        label31.setText("Font：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.EAST;
        control.add(label31, gbc);
        final JPanel spacer17 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer17, gbc);
        final JPanel spacer18 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer18, gbc);
        final JLabel label32 = new JLabel();
        label32.setText("Foreground：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 12;
        gbc.anchor = GridBagConstraints.EAST;
        control.add(label32, gbc);
        final JPanel spacer19 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 13;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer19, gbc);
        final JPanel spacer20 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 13;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer20, gbc);
        final JLabel label33 = new JLabel();
        label33.setText("Text：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 14;
        gbc.anchor = GridBagConstraints.EAST;
        control.add(label33, gbc);
        final JPanel spacer21 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 15;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer21, gbc);
        final JPanel spacer22 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 15;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer22, gbc);
        final JLabel label34 = new JLabel();
        label34.setText("Name：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 16;
        gbc.anchor = GridBagConstraints.EAST;
        control.add(label34, gbc);
        final JPanel spacer23 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 17;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer23, gbc);
        final JPanel spacer24 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 17;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer24, gbc);
        final JLabel label35 = new JLabel();
        label35.setText("Preferred Size：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 18;
        gbc.anchor = GridBagConstraints.EAST;
        control.add(label35, gbc);
        final JPanel spacer25 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 19;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer25, gbc);
        final JPanel spacer26 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 19;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer26, gbc);
        final JLabel label36 = new JLabel();
        label36.setAutoscrolls(true);
        label36.setDoubleBuffered(true);
        label36.setText("Visible：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 20;
        gbc.anchor = GridBagConstraints.EAST;
        control.add(label36, gbc);
        final JPanel spacer27 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 21;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer27, gbc);
        final JPanel spacer28 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 21;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer28, gbc);
        final JLabel label37 = new JLabel();
        label37.setText("Icon：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 22;
        gbc.anchor = GridBagConstraints.EAST;
        control.add(label37, gbc);
        final JPanel spacer29 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 23;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer29, gbc);
        final JPanel spacer30 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 23;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(spacer30, gbc);
        final JLabel label38 = new JLabel();
        label38.setText("ToolTips：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 24;
        gbc.anchor = GridBagConstraints.EAST;
        control.add(label38, gbc);
        cursorComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("DEFAULT_CURSOR");
        defaultComboBoxModel2.addElement("CROSSHAIR_CURSOR");
        defaultComboBoxModel2.addElement("TEXT_CURSOR");
        defaultComboBoxModel2.addElement("WAIT_CURSOR");
        defaultComboBoxModel2.addElement("SW_RESIZE_CURSOR");
        defaultComboBoxModel2.addElement("SE_RESIZE_CURSOR");
        defaultComboBoxModel2.addElement("NW_RESIZE_CURSOR");
        defaultComboBoxModel2.addElement("NE_RESIZE_CURSOR");
        defaultComboBoxModel2.addElement("N_RESIZE_CURSOR");
        defaultComboBoxModel2.addElement("S_RESIZE_CURSOR");
        defaultComboBoxModel2.addElement("W_RESIZE_CURSOR");
        defaultComboBoxModel2.addElement("E_RESIZE_CURSOR");
        defaultComboBoxModel2.addElement("HAND_CURSOR");
        defaultComboBoxModel2.addElement("MOVE_CURSOR");
        cursorComboBox.setModel(defaultComboBoxModel2);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.weightx = 100.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        control.add(cursorComboBox, gbc);
        enabledCheckBox = new JCheckBox();
        enabledCheckBox.setHorizontalAlignment(0);
        enabledCheckBox.setHorizontalTextPosition(11);
        enabledCheckBox.setText("enabled");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.VERTICAL;
        control.add(enabledCheckBox, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.BOTH;
        control.add(panel1, gbc);
        final JTextField textField1 = new JTextField();
        textField1.setColumns(10);
        textField1.setMinimumSize(new Dimension(61, 20));
        textField1.setOpaque(false);
        textField1.setText("");
        panel1.add(textField1);
        fontSelectButton = new JButton();
        fontSelectButton.setHideActionText(false);
        fontSelectButton.setHorizontalAlignment(0);
        fontSelectButton.setHorizontalTextPosition(0);
        fontSelectButton.setPreferredSize(new Dimension(30, 18));
        fontSelectButton.setRolloverEnabled(false);
        fontSelectButton.setText("...");
        fontSelectButton.setVerticalAlignment(0);
        panel1.add(fontSelectButton);
        foregroundColorChooserButton = new JButton();
        foregroundColorChooserButton.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        control.add(foregroundColorChooserButton, gbc);
        textTextField = new JTextField();
        textTextField.setMinimumSize(new Dimension(61, 20));
        textTextField.setOpaque(false);
        textTextField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 14;
        gbc.weightx = 100.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        control.add(textTextField, gbc);
        nameTextField = new JTextField();
        nameTextField.setMinimumSize(new Dimension(61, 20));
        nameTextField.setOpaque(false);
        nameTextField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 16;
        gbc.weightx = 100.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        control.add(nameTextField, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 5));
        panel2.setAlignmentX(0.0f);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 18;
        gbc.fill = GridBagConstraints.BOTH;
        control.add(panel2, gbc);
        preferredWidth = new JTextField();
        preferredWidth.setColumns(5);
        preferredWidth.setMinimumSize(new Dimension(61, 20));
        preferredWidth.setOpaque(false);
        preferredWidth.setText("");
        panel2.add(preferredWidth);
        preferredHeight = new JTextField();
        preferredHeight.setColumns(5);
        preferredHeight.setMinimumSize(new Dimension(61, 20));
        preferredHeight.setOpaque(false);
        preferredHeight.setText("");
        panel2.add(preferredHeight);
        visibleCheckBox = new JCheckBox();
        visibleCheckBox.setText("visible");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 20;
        gbc.anchor = GridBagConstraints.WEST;
        control.add(visibleCheckBox, gbc);
        iconButton = new JButton();
        iconButton.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 22;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        control.add(iconButton, gbc);
        toolTipsTextField = new JTextField();
        toolTipsTextField.setMinimumSize(new Dimension(61, 20));
        toolTipsTextField.setOpaque(false);
        toolTipsTextField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 24;
        gbc.weightx = 100.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        control.add(toolTipsTextField, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }

}
